# ??? ?????? Hilt + kapt ? Java 17+
kotlin.daemon.jvmargs=--add-opens=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED \
                      --add-opens=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED \
                      --add-opens=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
                      --add-opens=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
                      --add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED

org.gradle.jvmargs=--add-opens=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED \
                   -Xmx4g \
                   -XX:MaxMetaspaceSize=512m

# ?????? ?????????
org.gradle.parallel=true
org.gradle.daemon=true
android.useAndroidX=true
android.enableJetifier=true

